### ISSUE TITLE
I18n is not present on server side causing NoClassDefFoundError

### ISSUE THREAD

**Issue by makkarpov** [T145/metaltransport#14]
https://github.com/T145/metaltransport/blob/master/src/main/java/t145/metaltransport/entities/EntityMetalCart.java#L326

Server crashes when this line is executed, since I18n is a client-only class (`net.minecraft.client.resources.I18n`).

**Comment by ghost** [comment]
Appears to be the same issue here:

https://pastebin.com/q2eq2km9
