### ISSUE TITLE
All Carts Drop Vanilla Minecarts

### ISSUE THREAD

**Issue by WenXin20** [T145/metaltransport#5]
## Problem Details

- All carts from Metal Transport drop vanilla minecarts when broken instead of the copper, iron, silver, etc, minecarts.
- Right-Clicking the carts with a vanilla chest also turns it into a vanilla minecarts.
- Nothing was printed in the logs.

## Environment

- OS: Windows 10, Java 1.8.0_51 64 bit
- Full Forge version: v14.23.5.2838
- Metal Transport version: v2.0.6

**Comment by T145** [comment]
This is a known issue, as it's detailed in the release's TODO section on CurseForge.

**Comment by WenXin20** [comment]
I hadn't realized there was a TODO section.

**Comment by WenXin20** [comment]
In version 2.1.1, only the copper minecart drops itself. The rest drop vanilla minecarts, including the copper furnace minecart.

Placing the the copper minecart with the spawner from creative also crashed me when it was placed. I'll open a new issue for that.

**Comment by T145** [comment]
For me, in a fresh MC environment & in my development workspace there are no problems. Is there a way you can send a video detailing things? It doesn't have to include audio or anything, just be enough to show me your problem.

**Comment by WenXin20** [comment]
I'll see if I can get a video, but all I did was to take a Minecart from JEI, place it on rails, and then break it with a sword or by hand. Could the mod Charset Carts and Rails affect it?

**Comment by T145** [comment]
More than likely. I didn't know Charset was involved initially, that should help narrow down the scope.

**Comment by WenXin20** [comment]
Here's a [link](https://www.curseforge.com/minecraft/mc-mods/charset-transport-carts-and-rails) to it.

**Comment by WenXin20** [comment]
In the newest version, v2.4.0, only the empty minecarts drop themselves. The others drop vanilla minecarts.

**Comment by WenXin20** [comment]
I tested it without Charset, but the Minecarts still drop only the vanilla version if the cart is the crafted chest, furnace, or other special Minecarts.

**Comment by T145** [comment]
On the latest version? I've been unable to recreate this problem. If you could create a video clip of it happening on an instance where only Metal Transport and its dependencies are installed validating the issue I'll investigate further. As of now I've been unable to recreate it.
