### ISSUE TITLE
Crash w/ Cyclic 

### ISSUE THREAD

**Issue by WenXin20** [T145/metaltransport#6]
## Problem Details

- Right-clicking Cyclic's Stone Minecart onto a track crashes the game, while the gold minecart doesn't cause a crash.
- [Crash Log](https://paste.dimdev.org/afejefesiz.mccrash)

## Environment

- OS: Windows 10, Java 1.8.0_51 64 bit
- Full Forge version: v14.23.5.2838
- Metal Transport version: v2.0.6
- [Cyclic](https://www.curseforge.com/minecraft/mc-mods/cyclic) v1.19.12

**Comment by T145** [comment]
Have you whitelisted any of Cyclic's cart classes in the config file?

**Comment by WenXin20** [comment]
No, I haven't.
I'm not even sure how to do that.
