### ISSUE TITLE
Server Logs a memory leak with Metal Transport v2.1.1

### ISSUE THREAD

**Issue by Royal-Jelly** [T145/metaltransport#9]
Im not a hundred percent certain this is not because of my specific use case but here is my [**Full Paste Bin Log**](https://pastebin.com/cgvpGFDp) , and a Small Snip :
> [20:32:20] [Server thread/WARN] [minecraft/EntityDataManager]: defineId called for: class net.minecraft.entity.item.EntityMinecartEmpty from class t145.metaltransport.api.caps.CapabilityCartType

> Jul 13, 2019 9:01:17 PM io.netty.util.ResourceLeakDetector reportUntracedLeak
SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.

Environment:
-   OS: Linux Mint 19
-   Full Forge version: 14.23.5.2838 [1.12.2]
-   Mod version: Metal Transport 2.1.1

**Comment by T145** [comment]
I'm not too sure. Let me know if this issue persists in the next release, as there have been a good few changes to the system to bring back what I had before.

**Comment by T145** [comment]
Does this issue persist on the most recent release?
